Repository softwaremill/FoXAI, pull requests merged in 2023-08, with the labels that each got.

#99 Integrate XRAI repository with FoXAI
  example/notebooks/basic_usage.ipynb
  foxai/array_utils.py
  foxai/context_manager.py
  foxai/explainer/__init__.py
  foxai/explainer/computer_vision/algorithm/xrai.py
  foxai/explainer/fullgradient.py
  foxai/visualizer.py
  tests/explainers/computer_vision/algorithm/__init__.py
  tests/explainers/computer_vision/algorithm/test_xrai.py
  tests/test_array_utils.py
Labels: enhancement

#102 [Issue 84] Add table of explainers
  README.md
Labels: documentation

#118 Update examples code
  example/notebooks/basic_usage.ipynb
  example/notebooks/focus_metric_example.ipynb
  example/yolov5_exmaple/yolo_xai.py
  poetry.lock
  pyproject.toml
Labels: bug

#123 Add table with Google Colaboratory notebook link
  README.md
Labels: documentation

#88 Upgrade pandas, pytroch, pytorch-lightning
  foxai/metrics/insertion_deletion_metrics.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#122 WIP testing various package versions
  .github/actions/build-module/action.yaml
  .github/workflows/installation_test_auto_run.yaml
  .github/workflows/installation_test_called_workflow.yaml
  .github/workflows/installation_test_manual_run.yaml
Labels: enhancement, dependencies

#121 Input X Gradient prioprietary - Issue 110
  foxai/explainer/computer_vision/algorithm/gradient_utils.py
  foxai/explainer/computer_vision/algorithm/input_x_gradient.py
  tests/explainers/computer_vision/algorithm/test_gradient_utils.py
  tests/explainers/computer_vision/test_explainers.py
Labels: enhancement, prioprietary algo

#127 Proprietary implementation of Saliency algorithm
  foxai/explainer/computer_vision/algorithm/gradient_utils.py
  foxai/explainer/computer_vision/algorithm/input_x_gradient.py
  foxai/explainer/computer_vision/algorithm/saliency.py
  tests/explainers/computer_vision/test_explainers.py
Labels: enhancement, prioprietary algo
